### PR TITLE
Redirection to notification screen

### PR DESCRIPTION
**Pull request by venkylm10**
fixes: #115  
used GlobalKey<NavigatorState> to navigate to notification screen once user responds to push notifications

### CODE REVIEW

**Comment by venkylm10** [comment]
completed #130 
Completed UI
Only logged in user can access these pages
User current info will be shown once opened the these screens
Added some validation checks in the form

**Comment by venkylm10** [comment]
@Ashutosh-777 can you check this once
sorry by mistake i completed two issues(#115  and #130 ) in a single pull request

**Comment by Ashutosh-777** [comment]
> @Ashutosh-777 can you check this once sorry by mistake i completed two issues(#115 and #130 ) in a single pull request

Okay, will review both the issue!

**Comment by Ashutosh-777** [comment]
@venkylm10  make different PR for both the issue **Mark this Important!**

**Comment by venkylm10** [comment]
yeah will create new ones for both

**Pull request closed without merging**
